### User SignUp
POST {{local_host}}/v1/auth/signup
Accept: application/json
Content-Type: application/json

{
  "email": "mach@gmail.com",
  "password": "lothbrook11"
}



### User SignIn
POST {{local_host}}/v1/auth/signin
Accept: application/json
Content-Type: application/json

{
  "email": "mach@gmail.com",
  "password": "lothbrook11"
}



### User Logout
POST {{local_host}}/v1/auth/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{local_token}}




### Create Chat
POST {{local_host}}/v1/chat/message
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{local_token}}

{
  "message": "monster",
  "sender_id": 5,
  "receiver_id": 1
}



### Get Random API
GET https://andruxnet-random-famous-quotes.p.rapidapi.com/?count=10&cat=famous
Accept: application/json
Content-Type: application/json
X-RapidAPI-Key: 27a2e0ebeemsh5df4f3f8a5fb5dbp1f7057jsna26300dfaebb
X-RapidAPI-Host: andruxnet-random-famous-quotes.p.rapidapi.com
