### User SignUp
POST {{local_host}}/api/account/register
Accept: application/json
Content-Type: application/json

{
  "name": "moob deep",
  "email": "survival@gmail.com",
  "password": "lothbrook11"
}



### User SignIn
POST {{local_host}}/api/account/login
Accept: application/json
Content-Type: application/json

{
  "email": "survival@gmail.com",
  "password": "lothbrook11"
}



### User Logout
POST {{local_host}}/api/account/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{local_token}}



### Delete account
POST {{local_host}}/api/account/delete
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{local_token}}




### Recover account
POST {{local_host}}/api/account/recover
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{local_token}}



### Get profile
GET {{local_host}}/api/account/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{local_token}}




### Update profile
PATCH {{local_host}}/api/account/profile/update
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{local_token}}

{
  "name": "Ninja",
  "email": "jonjones@gmail.com"
}