### User SignUp
POST {{local_host}}/v1/auth/signup
Accept: application/json
Content-Type: application/json

{
  "email": "max.95@gmail.com",
  "password": "lothbrook11",
  "name": "yamato",
  "phone_number": "+995558669978"

}