basePath: /v1
definitions:
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: 167.99.246.163:7000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /account/delete:
    post:
      consumes:
      - application/json
      description: User account delete
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "401":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "422":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Delete user account with bearer token
      tags:
      - Delete user account
  /account/profile:
    get:
      consumes:
      - application/json
      description: Get account information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "422":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get account information
      tags:
      - Get account information
  /account/recover:
    post:
      consumes:
      - application/json
      description: User account recover
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "401":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "422":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Recover user account with bearer token
      tags:
      - Recover user account
  /auth/logout:
    post:
      consumes:
      - application/json
      description: User Sign out
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "401":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "422":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: User Sign out
      tags:
      - User Sign out with token
  /auth/signin:
    post:
      consumes:
      - application/json
      description: authenticate user
      parameters:
      - description: Email
        in: path
        name: email
        required: true
        type: string
      - description: Password
        in: path
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "422":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Sign In user generating jwt token
      tags:
      - User Authentication
  /auth/signup:
    post:
      consumes:
      - application/json
      description: register user
      parameters:
      - description: Email
        in: path
        name: email
        required: true
        type: string
      - description: Password
        in: path
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "422":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Sign up user generating jwt token
      tags:
      - User Registration
swagger: "2.0"
